services:
  backend:
    build: ./backend
    
    command: uvicorn api:app --reload --host 0.0.0.0 --port 5000
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
  nginx:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "5001:80"
    restart: always
