services:
  client:
    build: ./client
    ports:
      - "80:80"
    
  server:
    build: ./server
    command: uvicorn api:app --reload --host 0.0.0.0 --port 5000
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
